version: "3.3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      APP_FRONTEND_URL: http://frontend-host:80
      APP_FRONTEND_DOMAIN: frontend-host
      APP_BACKEND_URL: http://backend:8080
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SMTP_FROM: ${SMTP_FROM}
      EMAIL_LOGIN: ${EMAIL_LOGIN}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 8080
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network
  frontend-host:
    build:
      context: ./frontend/host
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/host/nginx:/etc/nginx/conf.d:ro
    environment:
      VITE_API_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network
  frontend-auth:
    build:
      context: ./frontend/auth
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./frontend/auth/nginx:/etc/nginx/conf.d:ro
    environment:
      VITE_API_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  adminpanel:
    build: ./adminpanel
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      DATABASE_DIALECT: postgres
      DATABASE_NAME: ${DB_NAME}
      DATABASE_HOST: postgres
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      COOKIE_SECRET: ${COOKIE_SECRET}
      PORT: 4000
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
